# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assets/Account_Transaction_Statement.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Account_Statement(object):
    def setupUi(self, Account_Statement):
        Account_Statement.setObjectName("Account_Statement")
        Account_Statement.resize(1270, 590)
        Account_Statement.setMinimumSize(QtCore.QSize(1270, 590))
        Account_Statement.setMaximumSize(QtCore.QSize(1270, 590))
        Account_Statement.setStyleSheet("#Account_Statement{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.02, y2:0.0340909, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(0, 0, 0, 199), stop:0.505 rgba(28, 28, 28, 255), stop:1 rgba(53, 53, 53, 255));\n"
"}\n"
"#topframe{\n"
"background-color: qconicalgradient(cx:0.000472637, cy:0, angle:227.8, stop:0 rgba(30, 0, 255, 255), stop:0.375 rgba(0, 195, 255, 252), stop:0.423533 rgba(37, 0, 255, 255), stop:0.45 rgba(0, 130, 255, 255), stop:0.477581 rgba(0, 56, 255, 252), stop:0.518717 rgba(71, 171, 255, 255), stop:0.542289 rgba(71, 171, 255, 255), stop:0.547264 rgba(68, 134, 249, 255), stop:0.55 rgba(0, 74, 255, 255), stop:0.552239 rgba(21, 93, 243, 255), stop:0.57754 rgba(102, 0, 255, 255), stop:0.625 rgba(0, 185, 255, 247), stop:1 rgba(255, 255, 0, 69));\n"
"border:none;\n"
"}\n"
"#bottomframe{\n"
"background-color: qlineargradient(spread:pad, x1:0.025, y1:0.892545, x2:0.0199005, y2:0, stop:0 rgba(244, 244, 244, 255), stop:0.495 rgba(218, 212, 186, 230), stop:0.505 rgba(236, 224, 224, 255), stop:1 rgba(253, 246, 246, 255));\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"background:#aaff00;\n"
"border:2px solid #aaff00;\n"
"font: 75 12pt \"MS Sans Serif\";\n"
"}\n"
"#Back_btn{\n"
"background:#aaff00;\n"
"}\n"
"QLineEdit{\n"
"border-radius:15px;\n"
"border-bottom:3px solid #aaff00;\n"
"}\n"
"#text{\n"
"color:white;\n"
"    font: 75 22pt \"MS Sans Serif\";\n"
"}\n"
"#label_3{\n"
"color:white;\n"
"}\n"
"#Account_Information_btn, #Users_Details_btn{\n"
"background:none;\n"
"border:none;\n"
"color:blue;\n"
"text-decoration: underline;\n"
"}\n"
"QTextEdit{\n"
"background:#e5fffe;\n"
"border-radius:15px;\n"
"}")
        self.bottomframe = QtWidgets.QFrame(Account_Statement)
        self.bottomframe.setGeometry(QtCore.QRect(10, 520, 1251, 61))
        self.bottomframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomframe.setObjectName("bottomframe")
        self.label = QtWidgets.QLabel(self.bottomframe)
        self.label.setGeometry(QtCore.QRect(490, 10, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bottomframe)
        self.label_2.setGeometry(QtCore.QRect(410, 30, 381, 16))
        self.label_2.setObjectName("label_2")
        self.sideframe = QtWidgets.QFrame(Account_Statement)
        self.sideframe.setGeometry(QtCore.QRect(9, 119, 151, 401))
        self.sideframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideframe.setObjectName("sideframe")
        self.Admin_Home_btn = QtWidgets.QPushButton(self.sideframe)
        self.Admin_Home_btn.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.Admin_Home_btn.setObjectName("Admin_Home_btn")
        self.User_Details_btn = QtWidgets.QPushButton(self.sideframe)
        self.User_Details_btn.setGeometry(QtCore.QRect(9, 112, 141, 31))
        self.User_Details_btn.setObjectName("User_Details_btn")
        self.Account_Details_btn = QtWidgets.QPushButton(self.sideframe)
        self.Account_Details_btn.setGeometry(QtCore.QRect(11, 162, 141, 31))
        self.Account_Details_btn.setObjectName("Account_Details_btn")
        self.Log_out_btn = QtWidgets.QPushButton(self.sideframe)
        self.Log_out_btn.setGeometry(QtCore.QRect(10, 212, 141, 31))
        self.Log_out_btn.setObjectName("Log_out_btn")
        self.text = QtWidgets.QLabel(Account_Statement)
        self.text.setGeometry(QtCore.QRect(480, 120, 391, 51))
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.label_3 = QtWidgets.QLabel(Account_Statement)
        self.label_3.setGeometry(QtCore.QRect(260, 169, 811, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.topframe = QtWidgets.QPushButton(Account_Statement)
        self.topframe.setGeometry(QtCore.QRect(10, 10, 1251, 101))
        self.topframe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets\\Images/Bank-Management-System.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.topframe.setIcon(icon)
        self.topframe.setIconSize(QtCore.QSize(1300, 520))
        self.topframe.setObjectName("topframe")
        self.Account_Details_table = QtWidgets.QTableWidget(Account_Statement)
        self.Account_Details_table.setGeometry(QtCore.QRect(280, 200, 751, 241))
        self.Account_Details_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Account_Details_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Account_Details_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Account_Details_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Account_Details_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Account_Details_table.setObjectName("Account_Details_table")
        self.Account_Details_table.setColumnCount(6)
        self.Account_Details_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Account_Details_table.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Account_Statement)
        QtCore.QMetaObject.connectSlotsByName(Account_Statement)

    def retranslateUi(self, Account_Statement):
        _translate = QtCore.QCoreApplication.translate
        Account_Statement.setWindowTitle(_translate("Account_Statement", "Bank Management System"))
        self.label.setText(_translate("Account_Statement", "Project by: Ankit Choudhary "))
        self.label_2.setText(_translate("Account_Statement", "ID: 19CS014   Anand International College of Engineering, Jaipur"))
        self.Admin_Home_btn.setText(_translate("Account_Statement", "Admin Home"))
        self.User_Details_btn.setText(_translate("Account_Statement", "User Details"))
        self.Account_Details_btn.setText(_translate("Account_Statement", "Account Details"))
        self.Log_out_btn.setText(_translate("Account_Statement", "Sign/Log out"))
        self.text.setText(_translate("Account_Statement", "Account Statement"))
        self.label_3.setText(_translate("Account_Statement", "View list of all credit/debit/fund transfer transaction summary by this user."))
        self.Account_Details_table.setSortingEnabled(True)
        item = self.Account_Details_table.horizontalHeaderItem(0)
        item.setText(_translate("Account_Statement", "Transaction Date"))
        item = self.Account_Details_table.horizontalHeaderItem(1)
        item.setText(_translate("Account_Statement", "Reference No#"))
        item = self.Account_Details_table.horizontalHeaderItem(2)
        item.setText(_translate("Account_Statement", "Transaction Description"))
        item = self.Account_Details_table.horizontalHeaderItem(3)
        item.setText(_translate("Account_Statement", "Debit"))
        item = self.Account_Details_table.horizontalHeaderItem(4)
        item.setText(_translate("Account_Statement", "Credit"))
        item = self.Account_Details_table.horizontalHeaderItem(5)
        item.setText(_translate("Account_Statement", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Account_Statement = QtWidgets.QWidget()
    ui = Ui_Account_Statement()
    ui.setupUi(Account_Statement)
    Account_Statement.show()
    sys.exit(app.exec_())
