# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assets/Admin_Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Home(object):
    def setupUi(self, Admin_Home):
        Admin_Home.setObjectName("Admin_Home")
        Admin_Home.resize(1270, 590)
        Admin_Home.setMinimumSize(QtCore.QSize(1270, 590))
        Admin_Home.setMaximumSize(QtCore.QSize(1270, 590))
        Admin_Home.setStyleSheet("#Admin_Home{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.02, y2:0.0340909, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(0, 0, 0, 199), stop:0.505 rgba(28, 28, 28, 255), stop:1 rgba(53, 53, 53, 255));\n"
"}\n"
"#topframe{\n"
"background-color: qconicalgradient(cx:0.000472637, cy:0, angle:227.8, stop:0 rgba(30, 0, 255, 255), stop:0.375 rgba(0, 195, 255, 252), stop:0.423533 rgba(37, 0, 255, 255), stop:0.45 rgba(0, 130, 255, 255), stop:0.477581 rgba(0, 56, 255, 252), stop:0.518717 rgba(71, 171, 255, 255), stop:0.542289 rgba(71, 171, 255, 255), stop:0.547264 rgba(68, 134, 249, 255), stop:0.55 rgba(0, 74, 255, 255), stop:0.552239 rgba(21, 93, 243, 255), stop:0.57754 rgba(102, 0, 255, 255), stop:0.625 rgba(0, 185, 255, 247), stop:1 rgba(255, 255, 0, 69));\n"
"border:none;\n"
"}\n"
"#bottomframe{\n"
"background-color: qlineargradient(spread:pad, x1:0.025, y1:0.892545, x2:0.0199005, y2:0, stop:0 rgba(244, 244, 244, 255), stop:0.495 rgba(218, 212, 186, 230), stop:0.505 rgba(236, 224, 224, 255), stop:1 rgba(253, 246, 246, 255));\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"background:#aaff00;\n"
"border:2px solid #aaff00;\n"
"font: 75 12pt \"MS Sans Serif\";\n"
"}\n"
"#Back_btn{\n"
"background:#aaff00;\n"
"}\n"
"QLineEdit{\n"
"border-radius:15px;\n"
"border-bottom:3px solid #aaff00;\n"
"}\n"
"#text{\n"
"color:white;\n"
"font: 75 28pt \"MS Sans Serif\";\n"
"}\n"
"#label_3{\n"
"color:white;\n"
"}\n"
"#Account_Information_btn, #Users_Details_btn{\n"
"background:none;\n"
"border:none;\n"
"color:blue;\n"
"text-decoration: underline;\n"
"}\n"
"QTextEdit{\n"
"background:#e5fffe;\n"
"border-radius:15px;\n"
"}")
        self.bottomframe = QtWidgets.QFrame(Admin_Home)
        self.bottomframe.setGeometry(QtCore.QRect(10, 520, 1251, 61))
        self.bottomframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomframe.setObjectName("bottomframe")
        self.label = QtWidgets.QLabel(self.bottomframe)
        self.label.setGeometry(QtCore.QRect(490, 10, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bottomframe)
        self.label_2.setGeometry(QtCore.QRect(410, 30, 381, 16))
        self.label_2.setObjectName("label_2")
        self.sideframe = QtWidgets.QFrame(Admin_Home)
        self.sideframe.setGeometry(QtCore.QRect(9, 119, 151, 401))
        self.sideframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideframe.setObjectName("sideframe")
        self.Admin_Home_btn = QtWidgets.QPushButton(self.sideframe)
        self.Admin_Home_btn.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.Admin_Home_btn.setObjectName("Admin_Home_btn")
        self.User_Details_btn = QtWidgets.QPushButton(self.sideframe)
        self.User_Details_btn.setGeometry(QtCore.QRect(9, 112, 141, 31))
        self.User_Details_btn.setObjectName("User_Details_btn")
        self.Account_Details_btn = QtWidgets.QPushButton(self.sideframe)
        self.Account_Details_btn.setGeometry(QtCore.QRect(11, 162, 141, 31))
        self.Account_Details_btn.setObjectName("Account_Details_btn")
        self.Log_out_btn = QtWidgets.QPushButton(self.sideframe)
        self.Log_out_btn.setGeometry(QtCore.QRect(10, 212, 141, 31))
        self.Log_out_btn.setObjectName("Log_out_btn")
        self.text = QtWidgets.QLabel(Admin_Home)
        self.text.setGeometry(QtCore.QRect(510, 150, 391, 51))
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.label_3 = QtWidgets.QLabel(Admin_Home)
        self.label_3.setGeometry(QtCore.QRect(430, 220, 531, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.topframe = QtWidgets.QPushButton(Admin_Home)
        self.topframe.setGeometry(QtCore.QRect(10, 10, 1251, 101))
        self.topframe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets\\Images/Bank-Management-System.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.topframe.setIcon(icon)
        self.topframe.setIconSize(QtCore.QSize(1300, 520))
        self.topframe.setObjectName("topframe")
        self.Account_Information_btn = QtWidgets.QCommandLinkButton(Admin_Home)
        self.Account_Information_btn.setGeometry(QtCore.QRect(280, 360, 271, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets\\Images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Account_Information_btn.setIcon(icon1)
        self.Account_Information_btn.setIconSize(QtCore.QSize(20, 20))
        self.Account_Information_btn.setObjectName("Account_Information_btn")
        self.Users_Details_btn = QtWidgets.QCommandLinkButton(Admin_Home)
        self.Users_Details_btn.setGeometry(QtCore.QRect(760, 360, 271, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets\\Images/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Users_Details_btn.setIcon(icon2)
        self.Users_Details_btn.setIconSize(QtCore.QSize(40, 40))
        self.Users_Details_btn.setObjectName("Users_Details_btn")
        self.textBrowser = QtWidgets.QTextBrowser(Admin_Home)
        self.textBrowser.setGeometry(QtCore.QRect(270, 360, 341, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Admin_Home)
        self.textBrowser_2.setGeometry(QtCore.QRect(750, 360, 341, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.raise_()
        self.textBrowser.raise_()
        self.bottomframe.raise_()
        self.sideframe.raise_()
        self.text.raise_()
        self.label_3.raise_()
        self.topframe.raise_()
        self.Account_Information_btn.raise_()
        self.Users_Details_btn.raise_()

        self.retranslateUi(Admin_Home)
        QtCore.QMetaObject.connectSlotsByName(Admin_Home)

    def retranslateUi(self, Admin_Home):
        _translate = QtCore.QCoreApplication.translate
        Admin_Home.setWindowTitle(_translate("Admin_Home", "Bank Management System"))
        self.label.setText(_translate("Admin_Home", "Project by: Ankit Choudhary "))
        self.label_2.setText(_translate("Admin_Home", "ID: 19CS014   Anand International College of Engineering, Jaipur"))
        self.Admin_Home_btn.setText(_translate("Admin_Home", "Admin Home"))
        self.User_Details_btn.setText(_translate("Admin_Home", "User Details"))
        self.Account_Details_btn.setText(_translate("Admin_Home", "Account Details"))
        self.Log_out_btn.setText(_translate("Admin_Home", "Sign/Log out"))
        self.text.setText(_translate("Admin_Home", "Admin Main Page"))
        self.label_3.setText(_translate("Admin_Home", "Chose a menu from the left navigation to get started"))
        self.Account_Information_btn.setText(_translate("Admin_Home", "Account Information"))
        self.Users_Details_btn.setText(_translate("Admin_Home", "User Details List"))
        self.textBrowser.setHtml(_translate("Admin_Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Get the account details of any customer,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">credit, debit funds from it or activate,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">de-activate fund transfers.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Admin_Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">    </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">View all your customer details,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Activate or Inactive  them for login to</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">the system, or delete them.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_Home = QtWidgets.QWidget()
    ui = Ui_Admin_Home()
    ui.setupUi(Admin_Home)
    Admin_Home.show()
    sys.exit(app.exec_())
