# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Input_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Input_Dialog(object):
    def setupUi(self, Input_Dialog):
        Input_Dialog.setObjectName("Input_Dialog")
        Input_Dialog.resize(372, 172)
        self.buttonBox = QtWidgets.QDialogButtonBox(Input_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 130, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Input_Dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.label.setObjectName("label")
        self.AccountNumber = QtWidgets.QLineEdit(Input_Dialog)
        self.AccountNumber.setGeometry(QtCore.QRect(160, 50, 191, 22))
        self.AccountNumber.setObjectName("AccountNumber")

        self.retranslateUi(Input_Dialog)
        self.buttonBox.accepted.connect(Input_Dialog.accept)
        self.buttonBox.rejected.connect(Input_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Input_Dialog)

    def retranslateUi(self, Input_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Input_Dialog.setWindowTitle(_translate("Input_Dialog", "Dialog"))
        self.label.setText(_translate("Input_Dialog", "Enter Account Number : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Input_Dialog = QtWidgets.QDialog()
    ui = Ui_Input_Dialog()
    ui.setupUi(Input_Dialog)
    Input_Dialog.show()
    sys.exit(app.exec_())
